# Generated by Django 6.0.6 on 2026-06-22 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0009_delete_producto_alter_servicio_duracion'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_usados', to='citas.servicio')),
            ],
        ),
    ]
