# Generated by Django 6.0.6 on 2026-06-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('servicio', models.CharField(max_length=100)),
                ('hora', models.CharField(max_length=20)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
            ],
        ),
    ]
