# Generated by Django 6.0.6 on 2026-06-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='barbero',
            field=models.CharField(default='Sin asignar', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20),
        ),
    ]
