# Generated by Django 4.2.11 on 2026-06-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_cita_barbero_cita_fecha_alter_cita_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
