# Generated by Django 4.2.11 on 2026-06-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_barbero_producto_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='adicionales',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
