# Generated by Django 6.0.6 on 2026-06-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_alter_barbero_id_alter_cita_id_alter_producto_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Finalizada', 'Finalizada')], default='Pendiente', max_length=20),
        ),
    ]
