# Generated by Django 6.0.6 on 2026-06-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0007_alter_cita_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20),
        ),
    ]
