# Generated by Django 6.0.6 on 2026-06-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0008_alter_cita_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='duracion',
            field=models.IntegerField(),
        ),
    ]
