# Generated by Django 6.0.6 on 2026-06-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0009_delete_producto_alter_servicio_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='productos',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
