# Generated by Django 6.0.6 on 2026-06-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('servicio', models.CharField(max_length=100)),
                ('adicionales', models.CharField(blank=True, default='', max_length=200)),
                ('productos', models.CharField(blank=True, default='', max_length=200)),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=20)),
                ('barbero', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
            ],
        ),
    ]
